language: ruby
rvm:
- 1.9.2
- 1.9.3
- 2.0
- 2.1
- 2.2
- ruby-head
- jruby-19mode
- jruby-20mode
- rbx-2
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  email: false
  slack:
    secure: udqUs5rLo5XXIM+PpqBDCTOEobzqnQs2Vq+eHOBaJggVSjfYrN6OYQAmZVBLIpysCJPcuZhZ64u93p2Zl+Yu9vJHXPnhFIBEmQlFybCjRIQtz1MMaeqZTMCO49avY+SCjBvXZV902PKJ8vVeeR2O3T5oj894JTejtAnXm5yEInNft3ODMsF+v3R5WFjD8cS+RWegZRotkbhQmQNrqCKxD7rZ3ufTyJuhpVnJPsUZVyaMJbWUWJRsessbl9nBxk3fFR74KXoURgEOv/OmbQD5AkVv1FkxGh0Y7wpn0aU9UOSmJZzzsXp/MaGNfZW7UwGx4iMtTa1YK+h+/fD3PNePfCPLZfvIvxnheIUn3Zrky9TDfK3KP9KHNuAtGdW3c5oxSCimRNTmx2MmsnbGO2sElR/u+Jxr+h0NO5xaBQBmHQeGKjv7VYv3Hexeac0I9lf6lQzmpk6XlstsPfht/Qwia/45RyEu2E8/s4OTFiKYgCBtpttkQ1VTvRowUPgHcuddldUKlI0j6CZlM2gpt9oLAQvzSmdlGX3j4Hpa6nCHILzW8vLoNHvMHTgjz6GU6RJwSj9JjIDkg1XCmq60EmQOKaacjEGXAG2plp0Fulm5THgU7WKnxC5PA+lrSgspmUFb8A0nmKG3tyuSOytVGBRAyu3FLEQih0xrPcZJ2rZ5T0s=
deploy:
  provider: rubygems
  api_key:
    secure: S1l31kWuX5LsEkvbmmGsp8auaQItXRDY/h1kwuiEc0uC+KWIeloYqdx+8oXDyaX8AB1SDuOncv3B+gmNMXOzmZpbrGXuESSJApwpG4R6+n1ubZgpiy9EOXA4XbwhNQtwUZXkvLR1XSUtCFDq5c6vokfNpMMO2zHCj8PqVc7cJZBDybhflUxlRpmm6SIy7FK28E1/E5lUAJXNMfuS4C7qNUzlJ1OcB8+6Sxvnw3756wMPBkfqaMxvksmX+sK206yiAS+BbTmmzh8sOKXbcZJ9/d7XntGe63h2kS5A3ncSOHEJoRWk3+m2NIjkdse2rhpM/oEMazY3D7lfShzDbcJN9BukPceMiG4lImubsw9iYFkRaToaF5kDsZR+G9+O4pTmqJ++1RpDVHuIOQdCGMmSV2JJFflOhO04IjdYdr9eKnhDWYMoufFZuYhmOLl2Fh8zqcw+AlAItKLaPOTtBW007J3+/SjFsBtUkVCH/y86q0iUbGxJ7/XikwTzhFfqLWu5+441g/11E2WqoAVm34Oa1jkEiWx7DSJEExdTNG60HFkDue97953vZ8Qi01SBnvGt6R1pHdrzPx7IdiTGKbxzblHqvyAd4sdo9hI9kxKru92jrC5rDBYQJdxyspWMLWGtfMnYpNKcQ9d/lDk+L3A7okNYkrjtMG03zUubjgzdQYQ=
  on:
    tags: true
