language: ruby
rvm:
- 1.9.2
- 1.9.3
- 2.0
- 2.1
- 2.2
- ruby-head
- jruby-19mode
- jruby-20mode
- rbx-2
matrix:
  allow_failures:
  - rvm: ruby-head
notifications:
  email: false
  slack:
    secure: udqUs5rLo5XXIM+PpqBDCTOEobzqnQs2Vq+eHOBaJggVSjfYrN6OYQAmZVBLIpysCJPcuZhZ64u93p2Zl+Yu9vJHXPnhFIBEmQlFybCjRIQtz1MMaeqZTMCO49avY+SCjBvXZV902PKJ8vVeeR2O3T5oj894JTejtAnXm5yEInNft3ODMsF+v3R5WFjD8cS+RWegZRotkbhQmQNrqCKxD7rZ3ufTyJuhpVnJPsUZVyaMJbWUWJRsessbl9nBxk3fFR74KXoURgEOv/OmbQD5AkVv1FkxGh0Y7wpn0aU9UOSmJZzzsXp/MaGNfZW7UwGx4iMtTa1YK+h+/fD3PNePfCPLZfvIvxnheIUn3Zrky9TDfK3KP9KHNuAtGdW3c5oxSCimRNTmx2MmsnbGO2sElR/u+Jxr+h0NO5xaBQBmHQeGKjv7VYv3Hexeac0I9lf6lQzmpk6XlstsPfht/Qwia/45RyEu2E8/s4OTFiKYgCBtpttkQ1VTvRowUPgHcuddldUKlI0j6CZlM2gpt9oLAQvzSmdlGX3j4Hpa6nCHILzW8vLoNHvMHTgjz6GU6RJwSj9JjIDkg1XCmq60EmQOKaacjEGXAG2plp0Fulm5THgU7WKnxC5PA+lrSgspmUFb8A0nmKG3tyuSOytVGBRAyu3FLEQih0xrPcZJ2rZ5T0s=
deploy:
  provider: rubygems
  api_key:
    secure: 0NHx5Awijw3viHWVO4UDfAGzDFyqx19TQWsrTZmctR7NRy4FvTxIW5bd7j2AynNHeourhvbhRfJ6dScgqUX/wgBUzNLRgARQiyaUuuMYenFLklPZBJexPi+JToSPc0q1f6cMlqal1HSPL/Sx+T9koKe22pze6eU9Hh2LiZDC1D3B8967vUdLX7na2mNzz4TabsJxTV7zLBVoNK7amB/nlN0vZbrHx48RHE1v+Z24bV2We9N7p5uwg3BXzDRr5AR9Kcens/39TCj9ixRN2Uo6IqGbqVEPyYywt53HnsiVIQphnS9zskMtqKvJzRZdSZoPuW2qABOEGXRraiMEi6TtV0Kfo9LYr+q/QhL9gfaHvZf6dfH+j34AKzyNTu2nP+fiIJm/7H1GcOuOBo6r8UDFoFlX+nOl+KAPh1YggEDExvSRRsx0KYnsH+GPDdPxBMOvx7xx3Q0cDKFn9Y5ypMF48Gl6KPdxZCMFSScwk/QHNbB2ql4gIipAjTkJllTEgHqdcMxTko/4ukq6MEsfDnVO7OsaeB2kR2Lwy7DtV+abfCjJl0L5Wu/qr8z+9TT3DAzOGZOcGDOc48XZbYbqwKH3CPORv0fq6fFsjeNQ3/UaXaOsFCJaz1qIe2ZR2vkdu4gxY6NiXSlsQrtIynoIeOz4Has0rMXUHwV9EGJfkgog5KE=
  on:
    tags: true
