language: ruby
rvm:
- 1.9.2
- 1.9.3
- 2.0
- 2.1
- 2.2
- ruby-head
- jruby-19mode
- jruby-20mode
- rbx-2
matrix:
  allow_failures:
  - rvm: ruby-head
notifications:
  email: false
  slack:
    secure: udqUs5rLo5XXIM+PpqBDCTOEobzqnQs2Vq+eHOBaJggVSjfYrN6OYQAmZVBLIpysCJPcuZhZ64u93p2Zl+Yu9vJHXPnhFIBEmQlFybCjRIQtz1MMaeqZTMCO49avY+SCjBvXZV902PKJ8vVeeR2O3T5oj894JTejtAnXm5yEInNft3ODMsF+v3R5WFjD8cS+RWegZRotkbhQmQNrqCKxD7rZ3ufTyJuhpVnJPsUZVyaMJbWUWJRsessbl9nBxk3fFR74KXoURgEOv/OmbQD5AkVv1FkxGh0Y7wpn0aU9UOSmJZzzsXp/MaGNfZW7UwGx4iMtTa1YK+h+/fD3PNePfCPLZfvIvxnheIUn3Zrky9TDfK3KP9KHNuAtGdW3c5oxSCimRNTmx2MmsnbGO2sElR/u+Jxr+h0NO5xaBQBmHQeGKjv7VYv3Hexeac0I9lf6lQzmpk6XlstsPfht/Qwia/45RyEu2E8/s4OTFiKYgCBtpttkQ1VTvRowUPgHcuddldUKlI0j6CZlM2gpt9oLAQvzSmdlGX3j4Hpa6nCHILzW8vLoNHvMHTgjz6GU6RJwSj9JjIDkg1XCmq60EmQOKaacjEGXAG2plp0Fulm5THgU7WKnxC5PA+lrSgspmUFb8A0nmKG3tyuSOytVGBRAyu3FLEQih0xrPcZJ2rZ5T0s=
deploy:
  provider: rubygems
  api_key:
    secure: LacsB7dgswcA1emeTiFU1UnyNNMfsJuMgYyQBtuWfi9PHtOIVwOuaSmO83pDZNaoYZ2bxk3dglPu4S38gEF2wtvsbdiOzyAZrVSMN0WRMPLOSoUvnHRvMPQyjwkOZqjWigRiJJs8yDsqV+FkaVUeHwWhDUU3WB2aOCBob9Je4Qbf5hMlLCGTncyUbYk/thYYf2OrM4DR1jFKr7/LNEjqoSeB68zFq3JbhXsuiK3KTuB1CZBIyCDviYgRBHlhfQV4r4AdITb0uNukLktwvXZQ0XBZCgy1PzNwN4xt8RfT/9ybCkpU5IvKxWsYnAzsi47umDKG/MiybIuYrOZaicpjWeJirYCa5+u3+ENH/0JmyS5E8CQnt1Tyzx7p31/dvpk+BSzc4gsmF+Px8qQrmCZrHr7Qq0LUyeXWQ0qBU7v9vVDZYyzM7hGxkYP6Iq2STmrFAhnl5nIbHkXvC4YjWdIt487+VdD4lLi9oBIPasqPGu/UBTJlGC1KF0ORtx00WwTzljuB9l/l2+Cjw2RbRv0QgnlLmvKYmaPrItItoLcVWjZzf0hva+iI1hSN5Qoyajl8TWRc5UnGBQjf4/EWD0FaK0DgyQ5XIklHnc3sierz/JsG0IWuNH9ZpC9LNgg7y+6FNvhi/3zkdmbGVwLtDn6AYaVnRAeBsBE8JdOm0znDCws=
  on:
    tags: true
