name: CI_CD

on: [push, pull_request]

permissions: {}
jobs:
  Unit_tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [
          '2.6', '2.7', '3.0', '3.1',
          jruby,
        ]
        os: [ubuntu-latest, macOS-latest, windows-latest]
        experimental: [false]
        include:
          # TruffleRuby on Windows may fail
          - ruby-version: truffleruby
            os: windows-latest
            experimental: true
          - ruby-version: truffleruby
            os: macOS-latest
            experimental: false
          - ruby-version: truffleruby
            os: ubuntu-latest
            experimental: false
    steps:
    - uses: actions/checkout@v3

    - name: Set up ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Run specs
      run: bundle exec rake

  Integration_tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    needs: Unit_tests
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [
          "2.7", "3.1"
        ]
        os: [
          ubuntu-latest,
          macOS-latest,
          # Disable windows due to an issue with binary encoding in the tests
          # windows-latest
        ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up ruby ${{ matrix.ruby-version }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Install dependencies
      run: |
        bundle install
    - name: Run tests
      env:
        TINIFY_KEY: ${{ secrets.TINIFY_KEY }}
      run: |
        bundle exec rake integration
  Publish:
    if: |
       github.repository == 'tinify/tinify-ruby' &&
       startsWith(github.ref, 'refs/tags') &&
       github.event_name == 'push'
    timeout-minutes: 10
    needs: [Unit_tests, Integration_tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: bundle install
      - name: Publish to RubyGems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"